# Generated by Django 4.1.4 on 2023-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='Nama',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='Pesan',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='Email',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
